### ISSUE TITLE
Build Datamaintain in Dockerfile

### ISSUE THREAD

**Issue by nroulon** [4sh/datamaintain#130]
At the moment, the Dockerfiles copy the CLI tar from the host. This admit that the user run a `./gradlew clean build` before he start to build image.

We should build Datamaintain in the Dockerfile.

Note : from 20.10.0 Docker allow to use a volume in a Dockerfile. I think it will be usefull for gradle.

**Comment by Lysoun** [comment]
I'm afraid that building Datamaintain in the Dockerfile will make the build way longer. Since there are 6 executions of the docker files, that will make 6 builds. I'd rather add the ```./gradlew clean build``` in the script used to produce all the images (```docker-build-push.sh```)

**Comment by nroulon** [comment]
Are you sure ? I do rather think that Docker will use his cache.

**Comment by Lysoun** [comment]
From what I've seen, the cache depends on the Dockerfile and since multiple Dockerfiles are used, there will be multiple builds.

**Comment by nroulon** [comment]
Ok, I think we can go with the build in the `sh` for the time being.

If we move to CI/CD we will need a solution for publishing images with docker, maybe by building a datamaintain image once and use it as base of mongo images.
