### ISSUE TITLE
Datamaintain print relative path of script

### ISSUE THREAD

**Issue by nroulon** [4sh/datamaintain#147]
When Datamaintain print script that will be exectuted, the script just print filename.
Add an argument --porcelain for print script file relative path from scan path.

Example :
scan.path=/scripts
if the scripts is in /scrips/version1/script.js then print `version1/script.js`

**Comment by asolovieff** [comment]
@nroulon --porcelain doit il être par défaut à true ou false ?

**Comment by nroulon** [comment]
I think it's just a flag like `porcelain` arg of `git status`, so false by default and true when `porcelain` is pass.
