### ISSUE TITLE
Regex ending with $

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#148]
Regex ending with $ do not work. Datamaintain seems to add a $ and a ^ at the end and beginning of regex on its own.

**Comment by Lysoun** [comment]
@nroulon You were the one to spot the problem. To reproduce, I executed the java mongo sample with the following identifier regex:
- ```^(.*)$```
- ```(.*?)_.*$```
- ```^(.*?)_.*$```

Nothing went wrong, the scripts were always executed and the identifiers correctly extracted. Could you help me reproduce the problem?

**Comment by nroulon** [comment]
I reproduce with the docker version on a projet :
a tag with regex :
```
--tag before="/path/*_BEFORE\.js"
```
work correctly while a tag
```
--tag before="/path/*_BEFORE\.js$"
```
show the warn message : 
```
WARNING: Tag(name=before) did not match any scripts
```

**Comment by Lysoun** [comment]
@nroulon Tags use glob matchers, which do not support the use of $ like a regex does. You can find more about the glob syntax [here](https://en.wikipedia.org/wiki/Glob_%28programming%29)
