### ISSUE TITLE
Hard coded librairy versions in some build.gradle

### ISSUE THREAD

**Issue by asolovieff** [4sh/datamaintain#166]
The build.gradle.kts of the modules driver-jdbc and driver-mongo both contain hard coded librairiy version : 
- implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.20.0")
- testImplementation("com.h2database:h2:1.4.200")

**Comment by zplusp** [comment]
Can I take this one ?

**Comment by Lysoun** [comment]
> Can I take this one ?

Sure! :D
