### ISSUE TITLE
README / Contributing should mention that mongo command line client is required

### ISSUE THREAD

**Issue by frankschmitt** [4sh/datamaintain#169]
The MongoDB tests require the `mongo` command line client. If mongo is not present in the PATH, all of them fail:

> Error while executed command : "mongo mongodb://localhost:27018/datamaintain-test --quiet --eval db.executedScripts.find({}, { "name": 1, "checksum": 1, "identifier": 1}).toArray()" - Cannot run program "mongo" (in directory "."): error=2, No such file or directory 

I couldn't find this dependency in the README or Contributing file.

**Comment by frankschmitt** [comment]
This seems to have changed in the last year - now, I get a failure due to missing ```mongosh```:

> Task :modules:driver-mongo:test
> 
> datamaintain.db.driver.mongo.MongoDriverTest
> 
>   should save output(String, MongoShell)
> 
>     Test [1] mongo:4.0, MONGO PASSED
>     Test [2] mongo:4.0, MONGOSH FAILED
> 
>     datamaintain.core.exception.DatamaintainProcessException: Error while executed command : "mongosh mongodb://localhost:49159/datamaintain-test --quiet --eval EJSON.stringify(db.executedScripts.insert({"_id":"7b38d9c4-cc6a-4cf6-8cc3-2e0eefd2c4f5","name":"script3.js","checksum":"d3d9446802a44259755d38e6d163e820","identifier":"","executionStatus":"OK","action":"RUN","executionDurationInMillis":0,"executionOutput":"test"}))" - Cannot run program "mongosh" (in directory "."): error=2, No such file or directory
>         at app//datamaintain.db.driver.mongo.MongoDriverTest.should save output(MongoDriverTest.kt:239)
> 
>

**Comment by Lysoun** [comment]
Since the mongo IT tests do try to pass with mongo and mongosh now, both are needed for the IT tests now, you're right. I'm going to add it in the contributing file.

**Comment by Lysoun** [comment]
@frankschmitt I added a little paragraph about it. What do you think?

**Comment by frankschmitt** [comment]
Looks good, thanks!
