### ISSUE TITLE
Github action to build docker packages upon tag push

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#189]
To release Datamaintain's various docker packages, one for each mongo version supported by Datamaintain, a bash script is used: `docker-build-push.sh`, in the CLI module. This script builds all the docker images and then pushes them on the github docker registry.

**What to do here:**
Set up a github action that builds those docker packages and pushes them to the github registry when a tag is pushed.

**Comment by tijmenstor** [comment]
@Lysoun is this still open and could you elaborate on it? :)

**Comment by Lysoun** [comment]
@Tijmen34 Yes, this is still open. I edited to description to make it clearer, please feel free to ask any questions you might have. If you are interested in this issue, I can even assign it to you!
I had already started working on that one but did not finish and switch to another task. My work is currently on branch `#189-gh-action-docker-package-cd`. Unfortunately, the action never quite worked (https://github.com/4sh/datamaintain/actions/workflows/publish_docker_packages.yaml). You can either try to fix what I made or start a new branch of your own, doing it from scratch, it's up to you 😄 I don't know much about github actions so my try may be very flawed 😅

**Comment by tijmenstor** [comment]
@Lysoun thanks for updating description, I'll take a look this week!
