### ISSUE TITLE
Remove docker package for Mongo 3

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#198]
Since it is not supported anymore by Mongo, let's stop creating docker packages for this version. 
Inside cli module, remove docker files for 3.2 & 3.6 and edit `docker-build-push` not to build packages for versions 3.2, 3.4 and 3.6
Also remove the versions 3.2, 3.4 and 3.6 from `AbstractMongoDbTest`

**Comment by AdityaJ7** [comment]
hi @Lysoun can i pick this up ?

**Comment by Lysoun** [comment]
Yes of course!

**Comment by AdityaJ7** [comment]
@Lysoun created a pr for the same

**Comment by Lysoun** [comment]
That was fast!

**Comment by AdityaJ7** [comment]
yeah, i think it was a small change

**Comment by AdityaJ7** [comment]
oh did it got edited ?

**Comment by Lysoun** [comment]
You were so fast that I had no time to add a missing point in the issue 😅

**Comment by AdityaJ7** [comment]
oh lol, i'll make the missing changes, no worries

**Comment by AdityaJ7** [comment]
updated the PR
