### ISSUE TITLE
Add check stage

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#41]
FR: 
CHECK : Vérifie l'état des scripts, que ce soit de manière unitaire ou bien les uns par rapport aux autres. Ex : l'ordre de jeu a changé, un script n'existe plus par rapport à l'execution précédente

Si activé en conf, vérifier que les scripts déjà joués (via MD5) existent toujours. Si ce n'est pas le cas alors erreur et on stoppe.
On essaye de voir si le script existe dans la liste des scripts à jouer via son nom et s'il est trouvé alors dans le rapport d'erreur on suggère que ce script pourrait avoir été modifié et on propose une ligne de commande pour pallier le problème.
Si  activé en conf, on vérifie l'ordre de jeu, en vérifiant que les scripts à jouer sont bien censés être joués après ceux déjà joués.
Si activé en conf, vérifier l'intégrité syntaxique du fichier. (si des libs existent)
Générer un rapport
Le logger si mode verbose
Le sauver si sauvegarde activée

**Comment by nroulon** [comment]
need to define with the team
