### ISSUE TITLE
Config to mark all as executed at first run

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#57]
Right now, when you setup Datamaintain on a project that already has scripts, you have to use the CLI. Of course, if there are scripts that you want to be run by Datamaintain and others you don't, the CLI should be used to mark the scripts wanted as executed. 
When you just want to mark all the scripts as executed at the first run of Datamaintain, you still have to run the CLI. It could be easier to just set that in the configuration and let Datamaintain to the job for you.
I would like your opinions @nroulon @driccio @mrenou about that idea.

**Comment by driccio** [comment]
Hello, I like the idea but I think it is not so simple.
If the option exists and is set, it needs to review our workflow to know if it is the first time we launch DataMaintain. Then what means "the first time we launch Datamaintain" ? Need to store a boolean ? If no scripts saved on DB then it means it is the first time ?

For that reason, I prefer to keep it simple and so force the developers to use the cli to mark scripts as exectued or use a tag to ignore them.

**Comment by nroulon** [comment]
Only in CLI mode ? Disable it on Kubernetes pods

**Comment by Lysoun** [comment]
Won't do.

**Comment by driccio** [comment]
We consider it is not a need. Such a feature will take "too much time" for a really specific case. As we have many options to manage that case, so we will not do it.
