### ISSUE TITLE
Créer un yaml pour faire un pod Kubernetes

### ISSUE THREAD

**Issue by nroulon** [4sh/datamaintain#61]
Créer un yaml permettant de démarrer un pod contenant datamaintain se connectant à un pod mongo (voir pod mongo client)

**Comment by nroulon** [comment]
2 images / yaml :

The first Pod execute datamaintain and then kill himself (like cron), second need to connect in bash execute manually

**Comment by xhanin** [comment]
I think a typical use case would be to use it as an init container of an app server - so it would be nice to provide the base docker image that an app would use to create a docker image with the scripts , and an example of init container configuration. 

Mmm, wait, maybe the init container is not a so good idea, it depends on how datamaintain handle parallelism and how the app server is configured regarding scaling - if k8s spawns several app servers, they will all try to run datamaintain at startup in parallel.

Moreover, using a init container implies that the app server won't start until the scripts are passed. I don't know if you have a flag in datamaintain to tell if a script should be run in stop the world mode (stop any app server activity when running) or if it can safely run in background. I f you support that an init container wouldn't fit the usage, it would have to be a job or even something with some kind of k8s coordination with the deployment of a new version. That's not straightforward, but it would be very interesting.

WDYT?

**Comment by nroulon** [comment]
I think init container is the way to go but like you said :
- Datamaintain does not handle parallelism. I don't know if the init pod can write a lock on K8S (K8S database ?). If not then the pod can setup a lock on mongo but it is not that elegant.
- We do not have a "stop the world or not" feature but I think it can be handle later

I pushed DockerFiles on the #61 branch, the init pod is the next feature on my list.

**Comment by xhanin** [comment]
Indeed, with an init container or with a migration handled by the app server you need to handle synchronisation. Using a lock in the DB would be ok IMHO - you already rely on the DB to list the migrations and their state, I think it would be ok to use it also to lock on migrations before starting them. Another option would be to use a k8s controller dedicated for datamaintain, it seems more elegant and but that's more work.
