### ISSUE TITLE
Autocomplete in CLI

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#70]

**Comment by Lysoun** [comment]
The Clikt documentation seems to have a section about that: https://ajalt.github.io/clikt/autocomplete/#enabling-completion

**Comment by frankschmitt** [comment]
I could give this one a try, if you like. One question: which shells should be supported? Bash, zsh, fish, ... ?
   (Clikt supports these three, so hopefully, they should be straightforward (apart from the Fish limitations mentioned in the docs))

**Comment by Lysoun** [comment]
I think bash and zsh would be enough!

**Comment by Lysoun** [comment]
@frankschmitt Since you are interested in this issue, I'm assigning it to you! We look forward to your PR :D

**Comment by frankschmitt** [comment]
Thanks!

**Comment by frankschmitt** [comment]
It's a little bit more complicated than I thought - the completion functionality has been added in Version 3.1.0, and there were some breaking changes in between. I'm working on it :-)

**Comment by frankschmitt** [comment]
I've finished the implementation (cleanup still needs to be done), but I'm having some troubles testing it.

I've tried mirroring the approach from PrintConfig.kt in this way:
``` 
         @Nested
         inner class GenerateCompletion {
            private val logger = LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME) as Logger
            private val testAppender = TestAppender()

            @BeforeEach
            fun setupLogger() {
                logger.addAppender(testAppender)
                testAppender.start()
            }

            @Test
            fun `should generate completion script for bash`() {
                // Given
                val argv = listOf(
                        "bash"
                )

                // When
                runAppWithGenerateCompletion(listOf(), argv)
                
                // Then
                var index = 0
                // it seems these assertion are never executed?
                expectThat("x").isEqualTo("yy")
                expectThat(testAppender.events) {
                    get { get(index++).message }.isEqualTo("#!/usr/bin/env zsh")
                }
            }
```

but it seems that my Assertions are never executed  after the runAppWithGenerateCompletion() call, and I'm unsure why that's the case. 

@Lysoun  Could you perhaps take a look at AppTest in my branch and tell me how I can validate that the output is as expected?

**Comment by Lysoun** [comment]
@frankschmitt I tried to run your tests and it seems that I don't reach the assertions either. I have these logs:

```#!/usr/bin/env bash
# Command completion for app
# Generated by Clikt

__skip_opt_eq() {
    # this takes advantage of the fact that bash functions can write to local
    # variables in their callers
    (( i = i + 1 ))
    if [[ "${COMP_WORDS[$i]}" == '=' ]]; then
          (( i = i + 1 ))
    fi
}

_app() {
  local i=1
  local in_param=''
  local fixed_arg_names=()
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        --version|--v|-v|-version)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        --generate-completion)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--generate-completion' || in_param=''
          continue
          ;;
        --working-directory-path|--wd)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--working-directory-path' || in_param=''
          continue
          ;;
        --config-file-path)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--config-file-path' || in_param=''
          continue
          ;;
        --db-type)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--db-type' || in_param=''
          continue
          ;;
        --db-uri)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--db-uri' || in_param=''
          continue
          ;;
        --trust-uri)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        --mongo-tmp-path)
          __skip_opt_eq
          (( i = i + 1 ))
          [[ ${i} -gt COMP_CWORD ]] && in_param='--mongo-tmp-path' || in_param=''
          continue
          ;;
        --config)
          __skip_opt_eq
          in_param=''
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      generate-completion)
        _app_generate_completion $(( i + 1 ))
        return
        ;;
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '--version --v -v -version --generate-completion --working-directory-path --wd --config-file-path --db-type --db-uri --trust-uri --mongo-tmp-path --config -h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --version)
      ;;
    --generate-completion)
      ;;
    --working-directory-path)
      ;;
    --config-file-path)
      ;;
    --db-type)
      COMPREPLY=($(compgen -W 'mongo jdbc' -- "${word}"))
      ;;
    --db-uri)
      ;;
    --trust-uri)
      ;;
    --mongo-tmp-path)
      ;;
    --config)
      ;;
    --help)
      ;;
    *)
      COMPREPLY=($(compgen -W 'generate-completion' -- "${word}"))
      ;;
  esac
}

_app_generate_completion() {
  local i=$1
  local in_param=''
  local fixed_arg_names=('SHELL')
  local vararg_name=''
  local can_parse_options=1

  while [[ ${i} -lt $COMP_CWORD ]]; do
    if [[ ${can_parse_options} -eq 1 ]]; then
      case "${COMP_WORDS[$i]}" in
        --)
          can_parse_options=0
          (( i = i + 1 ));
          continue
          ;;
        -h|--help)
          __skip_opt_eq
          in_param=''
          continue
          ;;
      esac
    fi
    case "${COMP_WORDS[$i]}" in
      *)
        (( i = i + 1 ))
        # drop the head of the array
        fixed_arg_names=("${fixed_arg_names[@]:1}")
        ;;
    esac
  done
  local word="${COMP_WORDS[$COMP_CWORD]}"
  if [[ "${word}" =~ ^[-] ]]; then
    COMPREPLY=($(compgen -W '-h --help' -- "${word}"))
    return
  fi

  # We're either at an option's value, or the first remaining fixed size
  # arg, or the vararg if there are no fixed args left
  [[ -z "${in_param}" ]] && in_param=${fixed_arg_names[0]}
  [[ -z "${in_param}" ]] && in_param=${vararg_name}

  case "${in_param}" in
    --help)
      ;;
    SHELL)
      COMPREPLY=($(compgen -W 'bash zsh fish' -- "${word}"))
      ;;
  esac
}

complete -F _app app
```

If I understand correctly, the way completion is handled is that a bash script is produced and the program stops there. That must be why we have this output and the tests do not run: the program exited because it was done. 
Such a generation should actually be used when a new version is released, it makes little sense to enable the user to create their own version of the CLI with completion. 

I'm sorry I did not look into that before. In my opinion, this is what would be nice to do:

- [ ] Create a little `BuildCliWithAutocomplete.kt` (or another name of your liking) file with a `main` that does build this nice shell script. You can take inspiration from `RebuildDocumentation.kt`. I think that you will need to use a subprocess to do so, retrieve its output and write it in your chosen path. I'm pretty sure that you could use `execAppInSubprocess` that we wrote in `AppSubProcessUtils.kt`, initially to test errors.
- [ ] Do your unit testings on that class, to ensure that it does generate the file, maybe at a specific path? Like, in the `build` folder. I honestly don't really know how you could check the generation besides checking the beginning of the file... Maybe add some tests to ensure that this shell file does a basic thing that the CLI does, like print a help. And of course feel free to play with and try to see if all completions are pertinent. I'll have a look on that before merging your PR, to ensure our completion is complete and helpful ✨ 
- [ ] Create a gradle task to release the CLI with autocompletion (again, you can see how it was done for `RebuildDocumentation`) 
- [ ] Update the documentation on how to make a release (https://github.com/frankschmitt/datamaintain/blob/feature/%2370-autocomplete-in-cli/docs/how-to-release.md): basically fill the CLI paragraph that we never filled because the releases were only done by me and I know how it works 😅

Is that all clear for you @frankschmitt?

**Comment by frankschmitt** [comment]
@Lysoun Sounds sensible to me. Thanks!

**Comment by frankschmitt** [comment]
@Lysoun Another (possibly stupid) question: as far as I can see, the application is simply called "app" (at least that's what I get when I download the v2.0.0 command line client and run it, as well as when I run the gradle tasks).

That seems rather unspecific for an autocompletion script - I'd have expected something like datamaintain (or perhaps something shorter like "dm" or similar). Am I missing something? Should the autocompletion indeed be generated for the "app" command?

**Comment by frankschmitt** [comment]
@Lysoun I updated the Pull Request a couple of days ago - would love to get your input on the new version :-)

**Comment by Lysoun** [comment]
Yes, I'll come back to you in the weekend. I've been busy but I still have your PR on my mind!
