### ISSUE TITLE
Can't declare tag with multiple globMatchers with CLI

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#72]
```./bin/cli --db-type mongo --mongo-uri mongodb://localhost:27017/my-db update-db --path my-path --identifier-regex "(.*?)_.*" --execution-mode DRY --tag ignore=[absolute-path-to-script1;absolute-path-to-script2] --blacklisted-tags ignore```

-->

```bash absolute-path-to-script2]: No such file or directory```

**Comment by nroulon** [comment]
The error is here : --tag ignore=[absolute-path-to-script1**;**absolute-path-to-script2]
The correct separator is **,** but the --help was incorrectly state that it is **;**. I fixed the help command.
