### ISSUE TITLE
Extract generic driver configuration

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#95]
In a driver configuration, the following properties : 
- ``db.DRIVER.uri`` 
- ``db.DRIVER.tmp.path ``
- ``db.DRIVER.client.path``
- ``db.DRIVER.print.output``
- ``db.DRIVER.save.output``
Are redundant. They could be unified, at least in the code.

**Comment by driccio** [comment]
Hello,

`db.mongo.uri`, `db.mongo.print.output` and `db.mongo.save.output` are non-specific mongo configs so yes they should be generified like that : `db.uri`, `db.print.output` and `db.save.output`
