### ISSUE TITLE
Restx mongo java sample

### ISSUE THREAD

**Issue by Lysoun** [4sh/datamaintain#96]
Provide a sample to show how to use Datamaintain using Restx, with the mongo driver. An option would be to write an Autostartable. Please put it with [other samples]( https://github.com/4sh/datamaintain/tree/dev/samples). and add a README to explain what your sample does. You can reuse what was done for the [java mongo sample](https://github.com/4sh/datamaintain/tree/dev/samples/java-mongo).

**Comment by nroulon** [comment]
I do not think the AutoStartable is a good idea because you create need to create component for that and the component will always be in memory.

I think the best way to do it in dev mode do it is to setup Datamaintain in the static main method. Like the java mongo sample.

**Comment by xhanin** [comment]
If you add it in the main method, it will only be called if you launch the app as a main, but not when deployed on an app server like Tomcat. You could define it in the init method of the servlet, but that would require overriding the default restx servlet, which seems overkill just for that. Therefore I think the AutoStartable is not so bad, just be careful to avoid keeping reference to a big data structure (in memory)

**Comment by xhanin** [comment]
Mmm, sorry, I see you were talking only of dev mode. If that's the use case, the `main` method approach is fine
